name: Build Game

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "**"              # every branch
      - "!no-build-**"    # unless marked as no-build

env:
  BUILD_TYPE: Release
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm-cache

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup caches
        uses: ./.github/actions/setup-cache
        with:
          host: linux
          target: linux

      - name: Setup Environment
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends build-essential ninja-build libgl-dev libwayland-dev xorg-dev libxkbcommon-dev

      - name: Create Build Environment
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: cmake $GITHUB_WORKSPACE -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{ github.workspace }}/build
        shell: bash
        run: |
          cmake --build . --config $BUILD_TYPE --target MinecraftPE --parallel
          cmake --build . --config $BUILD_TYPE --target MinecraftPE-server --parallel

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcpe-linux
          path: |
            ${{ github.workspace }}/build/MinecraftPE
            ${{ github.workspace }}/build/MinecraftPE-server

  build-macos:
    name: Build macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup caches
        uses: ./.github/actions/setup-cache
        with:
          host: mac
          target: mac

      - name: Create Build Environment
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Configure CMake
        working-directory: ${{ github.workspace }}/build
        run: cmake $GITHUB_WORKSPACE -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake --build . --config $BUILD_TYPE --target MinecraftPE --parallel
          cmake --build . --config $BUILD_TYPE --target MinecraftPE-server --parallel

      - name: Prepare macOS Artifacts
        working-directory: ${{ github.workspace }}/build
        run: |
          mkdir -p dist
          cp MinecraftPE dist/
          cp MinecraftPE-server dist/
          find _deps -name "*.dylib" -exec cp {} dist/ \;

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcpe-macos
          path: ${{ github.workspace }}/build/dist/

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ build-linux, build-macos ]
    if: github.event_name != "pull_request"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Declare Version Variables
        id: ref
        run: |
          if [ -f VERSION ]; then
            echo "version=$(cat VERSION | xargs)" >> $GITHUB_OUTPUT
          else
            echo "version=0.6.1" >> $GITHUB_OUTPUT
          fi
          echo "hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Zip Linux Client
        uses: vimtor/action-zip@v1.2
        with:
          files: mcpe-linux/MinecraftPE
          dest: minecraftpe-${{ steps.ref.outputs.hash }}-linux.zip

      - name: Zip Linux Server
        uses: vimtor/action-zip@v1.2
        with:
          files: mcpe-linux/MinecraftPE-server
          dest: minecraftpe-server-${{ steps.ref.outputs.hash }}-linux.zip

      - name: Zip macOS Artifacts
        uses: vimtor/action-zip@v1.2
        with:
          files: mcpe-macos/
          dest: minecraftpe-${{ steps.ref.outputs.hash }}-macos.zip

      - name: Zip Data
        uses: vimtor/action-zip@v1.2
        with:
          files: data
          recursive: true
          dest: data.zip

      - name: Update Development Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: dev
          name: "Development Release"
          body: |
            MinecraftPE development release for commit ${{ github.sha }}.
          files: |
            ./data.zip
            ./minecraftpe-server-${{ steps.ref.outputs.hash }}-linux.zip
            ./minecraftpe-${{ steps.ref.outputs.hash }}-linux.zip
            ./minecraftpe-${{ steps.ref.outputs.hash }}-macos.zip
